# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

variables: 
 -name: testVar
  value: "tteesstt"

jobs:
  - job: Test_Job
    displayName: Test_Job
    steps:
      - script: echo $(setvarStep.testVar)
        name: testvar
      - powershell: echo "##vso[task.setvariable variable=testVar;isOutput=true]this is the value"
        name: setvarStep
      - script: echo $(setvarStep.testVar)
        name: echovar

