# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

# variables: 
#  -name: testVar
#   value: "tteesstt"

jobs:
  - job: Test_Job
    displayName: Test_Job
    steps:
      - script: echo $(setvarStep.testVar)
        name: testvar
      - powershell: echo "##vso[task.setvariable variable=testVar;isOutput=true]this is the value"
                    Write-Host "##vso[task.setvariable variable=foo;]bar"
        name: setvarStep
        ${{ if eq(variables['foo'], 'bar') }}:
          - powershell: 
                        # $foo = $env:foo
                        # if ( "bar" -eq $foo )
                        # {
                        #     Write-Output "The condition was true"
                        #     Write-Host "The value of project_name is $env:foo"  
                        # }
                        # else
                        # {
                        #   Write-Output "The condition was false"
                        # }
                        exit 1
      - script: echo $(setvarStep.testVar)
        name: echovar

